package com.solvix.tabungan

import androidx.compose.runtime.staticCompositionLocalOf
import java.util.Locale

enum class AppLanguage { ID, EN }

data class AppStrings(val map: Map<String, String>) {
  operator fun get(key: String): String = map[key] ?: key
}

val LocalStrings = staticCompositionLocalOf { stringsFor(AppLanguage.ID) }
val LocalLanguage = staticCompositionLocalOf { AppLanguage.ID }

enum class OptionList {
  Countries,
  IncomeSources,
  IncomeChannels,
  ExpenseMethods,
  ExpenseBanks,
}

fun stringsFor(language: AppLanguage): AppStrings {
  val id = mapOf(
    "app_name" to "CashFlow",
    "app_tagline" to "Catatan keuangan harian",
    "guest" to "Guest",
    "welcome_title" to "Selamat Datang!",
    "welcome_subtitle" to "Masuk untuk mulai mengelola tabunganmu.",
    "welcome_action" to "Masuk Aplikasi",
    "loading" to "Memuat...",
    "footer" to "Solvix Studio © 2026",
    "logo_alt" to "Logo Solvix Studio",
    "close" to "Tutup",
    "auth_sign_in" to "Sign In",
    "auth_sign_up" to "Sign Up",
    "auth_login" to "Masuk",
    "auth_register" to "Buat Akun",
    "auth_fingerprint" to "Masuk dengan Fingerprint",
    "confirm_title" to "Konfirmasi",
    "confirm_cancel" to "Batal",
    "confirm_ok" to "Ya, Lanjut",
    "alert_title" to "Info",
    "ok" to "Oke",
    "logout_success" to "Berhasil logout",
    "logout_confirm" to "Keluar dari akun ini?",
    "confirm_theme_change" to "Ganti tema ke",
    "confirm_delete_income" to "Hapus pemasukkan ini?",
    "confirm_delete_expense" to "Hapus pengeluaran ini?",
    "confirm_delete_dream" to "Hapus target ini?",
    "save_profile" to "Simpan Profil",
    "save_profile_failed" to "Gagal menyimpan profil. Coba lagi.",
    "save_income" to "Simpan Pemasukkan",
    "update_income" to "Update Pemasukkan",
    "save_expense" to "Simpan Pengeluaran",
    "update_expense" to "Update Pengeluaran",
    "save_dream" to "Simpan Target",
    "update_dream" to "Update Target",
    "save_password" to "Simpan Password",
    "export_pdf" to "Export PDF",
    "export_csv" to "Export CSV",
    "export_success_pdf" to "PDF berhasil diekspor",
    "export_success_csv" to "CSV berhasil diekspor",
    "export_failed" to "Export gagal",
    "edit" to "Edit",
    "delete" to "Hapus",
    "page_income" to "Pemasukkan",
    "page_expense" to "Pengeluaran",
    "page_dreams" to "Target",
    "page_history" to "History",
    "page_calculator" to "Kalkulator",
    "page_report" to "Laporan",
    "page_profile" to "Profile",
    "page_settings" to "Pengaturan",
    "page_themes" to "Tema",
    "menu_theme" to "Tema",
    "menu_admin" to "Admin",
    "menu_calculator" to "Kalkulator",
    "menu_report" to "Laporan",
    "menu_profile" to "Profile",
    "menu_settings" to "Pengaturan",
    "menu_logout" to "Keluar",
    "label_name" to "Nama",
    "label_username" to "Username",
    "label_email" to "Email",
    "label_country" to "Negara",
    "label_birthdate" to "Tanggal Lahir",
    "label_bio" to "Bio Singkat",
    "label_amount" to "Nominal",
    "label_date" to "Tanggal",
    "label_category" to "Kategori",
    "label_note" to "Catatan",
    "label_source" to "Sumber Pemasukkan",
    "label_channel" to "Masuk ke",
    "label_method" to "Metode Pembayaran",
    "label_bank" to "Bank / Wallet",
    "label_goal" to "Tujuan",
    "label_target_name" to "Nama Target",
    "label_target_amount" to "Target Dana",
    "label_target_current" to "Dana Terkumpul",
    "label_deadline" to "Deadline",
    "placeholder_date" to "DD-MM-YYYY",
    "placeholder_country" to "Pilih negara",
    "placeholder_source" to "Pilih sumber",
    "placeholder_channel" to "Pilih rekening",
    "placeholder_method" to "Pilih metode",
    "placeholder_bank" to "Pilih bank/wallet",
    "placeholder_category_income" to "Gaji, bonus, dll",
    "placeholder_category_expense" to "Makan, transport, dll",
    "placeholder_goal" to "Dana darurat, liburan",
    "placeholder_target" to "Contoh: Laptop baru",
    "placeholder_note" to "Detail tambahan",
    "placeholder_strategy" to "Strategi untuk target",
    "section_income_title" to "Pemasukkan",
    "section_income_subtitle" to "Catat semua pemasukkanmu dengan rapi.",
    "section_expense_title" to "Pengeluaran",
    "section_expense_subtitle" to "Kontrol pengeluaran supaya tetap aman.",
    "section_dreams_title" to "Target",
    "section_dreams_subtitle" to "Visualisasikan targetmu dan lihat progresnya.",
    "section_history_title" to "History",
    "section_history_subtitle" to "Riwayat transaksi pemasukkan dan pengeluaran.",
    "section_report_title" to "Laporan",
    "section_profile_title" to "Profile",
    "section_profile_subtitle" to "Data biodata ditampilkan di sini.",
    "section_settings_title" to "Pengaturan",
    "section_settings_subtitle" to "Kelola bahasa dan keamanan akun.",
    "section_themes_title" to "Ganti Tema",
    "section_themes_subtitle" to "Pilih tema favoritmu: kartun atau standard.",
    "summary_title" to "Ringkasan",
    "summary_range_month" to "Bulan ini",
    "summary_range_today" to "Hari ini",
    "summary_range_week" to "Minggu ini",
    "summary_range_year" to "Tahun ini",
    "summary_range_all" to "Semua",
    "summary_income" to "Pemasukkan",
    "summary_expense" to "Pengeluaran",
    "summary_balance" to "Saldo",
    "summary_period" to "Ringkasan Periode",
    "list_income" to "Daftar Pemasukkan",
    "list_expense" to "Daftar Pengeluaran",
    "list_dreams" to "Daftar Target",
    "no_transactions" to "Belum ada transaksi.",
    "from" to "Dari",
    "to" to "Sampai",
    "calculator_title" to "Kalkulator",
    "calculator_subtitle" to "Hitung cepat kebutuhan keuanganmu.",
    "report_monthly" to "Bulanan",
    "report_yearly" to "Tahunan",
    "report_mode" to "Mode",
    "report_total_income" to "Total pemasukkan",
    "report_total_expense" to "Total pengeluaran",
    "report_total_balance" to "Total saldo periode",
    "profile_update" to "Update Biodata",
    "settings_language" to "Bahasa",
    "settings_security" to "Keamanan",
    "settings_fingerprint" to "Login dengan Fingerprint",
    "settings_fingerprint_desc" to "Butuh fingerprint aktif & lockscreen",
    "settings_change_password" to "Ganti Password",
    "password_current" to "Password Saat Ini",
    "password_new" to "Password Baru",
    "password" to "Password",
    "password_confirm" to "Konfirmasi Password",
    "theme_standard_light" to "Standard Light",
    "theme_standard_dark" to "Standard Dark",
    "theme_food" to "Kartun Makanan",
    "theme_space" to "Kartun Luar Angkasa",
    "theme_monster" to "Kartun Monster",
    "theme_hero" to "Kartun Superhero",
    "theme_sea" to "Kartun Laut",
    "theme_plant" to "Kartun Tanaman",
    "theme_pinky" to "Kartun Pinky",
    "theme_colorful" to "Kartun Colorful",
    "fingerprint_enabled" to "Fingerprint login aktif.",
    "fingerprint_activity_required" to "Fingerprint membutuhkan FragmentActivity.",
    "fingerprint_required" to "Aktifkan fingerprint dan lockscreen dulu.",
    "fingerprint_prompt_title" to "Login dengan Fingerprint",
    "fingerprint_prompt_subtitle" to "Gunakan sidik jari untuk masuk",
    "exit_confirm" to "Apakah anda ingin keluar dari aplikasi?",
    "login_success" to "Login berhasil",
    "income_added" to "Pemasukkan berhasil ditambahkan",
    "income_updated" to "Pemasukkan berhasil diperbarui",
    "expense_added" to "Pengeluaran berhasil ditambahkan",
    "expense_updated" to "Pengeluaran berhasil diperbarui",
    "dream_added" to "Target berhasil ditambahkan",
    "dream_updated" to "Target berhasil diperbarui",
    "signup_success" to "Akun berhasil dibuat",
    "signup_missing" to "Lengkapi data pendaftaran dulu.",
    "signup_exists" to "Akun sudah terdaftar. Silakan masuk.",
    "admin_title" to "Admin Login",
    "admin_username" to "Username Admin",
    "admin_password" to "Password Admin",
    "admin_login" to "Masuk Admin",
    "admin_login_failed" to "Akses admin ditolak.",
    "admin_users_title" to "Pengguna Terdaftar",
    "admin_no_users" to "Belum ada pengguna terdaftar.",
    "admin_logout" to "Keluar Admin",
    "admin_dashboard_title" to "Dashboard Admin",
    "admin_dashboard_subtitle" to "Ringkasan statistik pengguna.",
    "admin_overview" to "Ringkasan",
    "admin_total_users" to "Total Pengguna",
    "admin_top_country" to "Negara Terbanyak",
    "admin_latest_signup" to "Pendaftaran Terbaru",
    "admin_chart_country" to "Sebaran Negara Pengguna",
    "admin_chart_recency" to "Aktivitas Pendaftaran",
    "admin_recency_7d" to "7 hari terakhir",
    "admin_recency_30d" to "30 hari terakhir",
    "admin_recency_90d" to "90 hari terakhir",
    "admin_recency_older" to "Lebih lama",
    "admin_recency_unknown" to "Tidak diketahui",
    "admin_other" to "Lainnya",
    "admin_unknown_country" to "Tidak diketahui",
    "goal_missing" to "Lengkapi semua data target dulu (catatan boleh kosong).",
    "goal_reached_single" to "Target tercapai: {title}",
    "goal_reached_multi" to "{count} target sudah tercapai.",
    "goal_deadline_title" to "Pengingat Deadline Target",
    "goal_deadline_body" to "{title} ({days}). Progres {current} / {target} ({percent}%).",
    "deadline_today" to "Hari H",
    "note_label" to "Note",
    "signin_missing" to "Masukkan username dan password.",
    "signin_failed" to "Username atau password salah.",
  )

  val en = mapOf(
    "app_name" to "CashFlow",
    "app_tagline" to "Daily finance tracker",
    "guest" to "Guest",
    "welcome_title" to "Welcome!",
    "welcome_subtitle" to "Sign in to start managing your savings.",
    "welcome_action" to "Enter App",
    "loading" to "Loading...",
    "footer" to "Solvix Studio © 2026",
    "logo_alt" to "Solvix Studio logo",
    "close" to "Close",
    "auth_sign_in" to "Sign In",
    "auth_sign_up" to "Sign Up",
    "auth_login" to "Sign In",
    "auth_register" to "Create Account",
    "auth_fingerprint" to "Sign in with Fingerprint",
    "confirm_title" to "Confirm",
    "confirm_cancel" to "Cancel",
    "confirm_ok" to "Yes, Continue",
    "alert_title" to "Info",
    "ok" to "OK",
    "logout_success" to "Logged out successfully",
    "logout_confirm" to "Sign out of this account?",
    "confirm_theme_change" to "Change theme to",
    "confirm_delete_income" to "Delete this income?",
    "confirm_delete_expense" to "Delete this expense?",
    "confirm_delete_dream" to "Delete this goal?",
    "save_profile" to "Save Profile",
    "save_profile_failed" to "Failed to save profile. Please try again.",
    "save_income" to "Save Income",
    "update_income" to "Update Income",
    "save_expense" to "Save Expense",
    "update_expense" to "Update Expense",
    "save_dream" to "Save Goal",
    "update_dream" to "Update Goal",
    "save_password" to "Save Password",
    "export_pdf" to "Export PDF",
    "export_csv" to "Export CSV",
    "export_success_pdf" to "PDF exported",
    "export_success_csv" to "CSV exported",
    "export_failed" to "Export failed",
    "edit" to "Edit",
    "delete" to "Delete",
    "page_income" to "Income",
    "page_expense" to "Expense",
    "page_dreams" to "Goals",
    "page_history" to "History",
    "page_calculator" to "Calculator",
    "page_report" to "Report",
    "page_profile" to "Profile",
    "page_settings" to "Settings",
    "page_themes" to "Themes",
    "menu_theme" to "Themes",
    "menu_admin" to "Admin",
    "menu_calculator" to "Calculator",
    "menu_report" to "Report",
    "menu_profile" to "Profile",
    "menu_settings" to "Settings",
    "menu_logout" to "Logout",
    "label_name" to "Name",
    "label_username" to "Username",
    "label_email" to "Email",
    "label_country" to "Country",
    "label_birthdate" to "Birthdate",
    "label_bio" to "Bio",
    "label_amount" to "Amount",
    "label_date" to "Date",
    "label_category" to "Category",
    "label_note" to "Note",
    "label_source" to "Income Source",
    "label_channel" to "Deposit To",
    "label_method" to "Payment Method",
    "label_bank" to "Bank / Wallet",
    "label_goal" to "Goal",
    "label_target_name" to "Goal Name",
    "label_target_amount" to "Target Amount",
    "label_target_current" to "Collected",
    "label_deadline" to "Deadline",
    "placeholder_date" to "DD-MM-YYYY",
    "placeholder_country" to "Select country",
    "placeholder_source" to "Select source",
    "placeholder_channel" to "Select account",
    "placeholder_method" to "Select method",
    "placeholder_bank" to "Select bank/wallet",
    "placeholder_category_income" to "Salary, bonus, etc",
    "placeholder_category_expense" to "Food, transport, etc",
    "placeholder_goal" to "Emergency fund, trip",
    "placeholder_target" to "Example: New laptop",
    "placeholder_note" to "Additional details",
    "placeholder_strategy" to "Strategy for goal",
    "section_income_title" to "Income",
    "section_income_subtitle" to "Track your income neatly.",
    "section_expense_title" to "Expense",
    "section_expense_subtitle" to "Keep spending under control.",
    "section_dreams_title" to "Goals",
    "section_dreams_subtitle" to "Visualize your goals and track progress.",
    "section_history_title" to "History",
    "section_history_subtitle" to "Income and expense history.",
    "section_report_title" to "Report",
    "section_profile_title" to "Profile",
    "section_profile_subtitle" to "Your profile data is shown here.",
    "section_settings_title" to "Settings",
    "section_settings_subtitle" to "Manage language and security.",
    "section_themes_title" to "Themes",
    "section_themes_subtitle" to "Pick your favorite theme.",
    "summary_title" to "Summary",
    "summary_range_month" to "This month",
    "summary_range_today" to "Today",
    "summary_range_week" to "This week",
    "summary_range_year" to "This year",
    "summary_range_all" to "All",
    "summary_income" to "Income",
    "summary_expense" to "Expense",
    "summary_balance" to "Balance",
    "summary_period" to "Period Summary",
    "list_income" to "Income List",
    "list_expense" to "Expense List",
    "list_dreams" to "Goals List",
    "no_transactions" to "No transactions yet.",
    "from" to "From",
    "to" to "To",
    "calculator_title" to "Calculator",
    "calculator_subtitle" to "Quickly calculate your finances.",
    "report_monthly" to "Monthly",
    "report_yearly" to "Yearly",
    "report_mode" to "Mode",
    "report_total_income" to "Total income",
    "report_total_expense" to "Total expense",
    "report_total_balance" to "Total period balance",
    "profile_update" to "Update Profile",
    "settings_language" to "Language",
    "settings_security" to "Security",
    "settings_fingerprint" to "Fingerprint Login",
    "settings_fingerprint_desc" to "Requires fingerprint & lockscreen",
    "settings_change_password" to "Change Password",
    "password_current" to "Current Password",
    "password_new" to "New Password",
    "password" to "Password",
    "password_confirm" to "Confirm Password",
    "theme_standard_light" to "Standard Light",
    "theme_standard_dark" to "Standard Dark",
    "theme_food" to "Food Cartoon",
    "theme_space" to "Space Cartoon",
    "theme_monster" to "Monster Cartoon",
    "theme_hero" to "Hero Cartoon",
    "theme_sea" to "Sea Cartoon",
    "theme_plant" to "Plant Cartoon",
    "theme_pinky" to "Pinky Cartoon",
    "theme_colorful" to "Colorful Cartoon",
    "fingerprint_enabled" to "Fingerprint login enabled.",
    "fingerprint_activity_required" to "Fingerprint requires a FragmentActivity.",
    "fingerprint_required" to "Enable fingerprint and lockscreen first.",
    "fingerprint_prompt_title" to "Fingerprint Login",
    "fingerprint_prompt_subtitle" to "Use your fingerprint to sign in",
    "exit_confirm" to "Do you want to exit the app?",
    "login_success" to "Login successful",
    "income_added" to "Income added successfully",
    "income_updated" to "Income updated",
    "expense_added" to "Expense added successfully",
    "expense_updated" to "Expense updated",
    "dream_added" to "Goal added successfully",
    "dream_updated" to "Goal updated",
    "signup_success" to "Account created",
    "signup_missing" to "Please complete the sign up form.",
    "signup_exists" to "Account already registered. Please sign in.",
    "admin_title" to "Admin Login",
    "admin_username" to "Admin Username",
    "admin_password" to "Admin Password",
    "admin_login" to "Admin Sign In",
    "admin_login_failed" to "Admin access denied.",
    "admin_users_title" to "Registered Users",
    "admin_no_users" to "No registered users yet.",
    "admin_logout" to "Admin Logout",
    "admin_dashboard_title" to "Admin Dashboard",
    "admin_dashboard_subtitle" to "User statistics overview.",
    "admin_overview" to "Overview",
    "admin_total_users" to "Total Users",
    "admin_top_country" to "Top Country",
    "admin_latest_signup" to "Latest Signup",
    "admin_chart_country" to "Users by Country",
    "admin_chart_recency" to "Signup Recency",
    "admin_recency_7d" to "Last 7 days",
    "admin_recency_30d" to "Last 30 days",
    "admin_recency_90d" to "Last 90 days",
    "admin_recency_older" to "Older",
    "admin_recency_unknown" to "Unknown",
    "admin_other" to "Other",
    "admin_unknown_country" to "Unknown",
    "goal_missing" to "Please complete the goal form (notes can be empty).",
    "goal_reached_single" to "Goal reached: {title}",
    "goal_reached_multi" to "{count} goals reached.",
    "goal_deadline_title" to "Goal Deadline Reminder",
    "goal_deadline_body" to "{title} ({days}). Progress {current} / {target} ({percent}%).",
    "deadline_today" to "Due today",
    "note_label" to "Note",
    "signin_missing" to "Enter username and password.",
    "signin_failed" to "Incorrect username or password.",
  )

  return AppStrings(if (language == AppLanguage.ID) id else en)
}

fun optionList(language: AppLanguage, list: OptionList): List<String> {
  return when (list) {
    OptionList.Countries -> if (language == AppLanguage.ID) {
      allCountries(Locale("id", "ID"))
    } else {
      allCountries(Locale.ENGLISH)
    }
    OptionList.IncomeSources -> if (language == AppLanguage.ID) {
      listOf("Kerja", "Bisnis", "Freelance", "Bonus", "Tabungan", "Investasi", "Lainnya")
    } else {
      listOf("Salary", "Business", "Freelance", "Bonus", "Savings", "Investment", "Other")
    }
    OptionList.IncomeChannels -> if (language == AppLanguage.ID) {
      listOf("BCA", "SeaBank", "Mandiri", "BNI", "BRI", "Cash", "E-Wallet", "Lainnya")
    } else {
      listOf("BCA", "SeaBank", "Mandiri", "BNI", "BRI", "Cash", "E-Wallet", "Other")
    }
    OptionList.ExpenseMethods -> if (language == AppLanguage.ID) {
      listOf("Transfer", "QRIS", "Cash", "Debit", "Kredit")
    } else {
      listOf("Transfer", "QRIS", "Cash", "Debit", "Credit")
    }
    OptionList.ExpenseBanks -> if (language == AppLanguage.ID) {
      listOf("BCA", "SeaBank", "Mandiri", "BNI", "BRI", "DANA", "OVO", "GoPay", "ShopeePay", "Cash", "Lainnya")
    } else {
      listOf("BCA", "SeaBank", "Mandiri", "BNI", "BRI", "DANA", "OVO", "GoPay", "ShopeePay", "Cash", "Other")
    }
  }
}

private fun allCountries(locale: Locale): List<String> {
  return Locale.getISOCountries()
    .map { code -> Locale("", code).getDisplayCountry(locale) }
    .filter { it.isNotBlank() }
    .distinct()
    .sorted()
}
